/******************************************************************************
 *
 * Caustik's Xbox Executable Library Project
 *
 * Copyright (c) 2007, Aaron "Caustik" Robinson
 * All rights reserved.
 * 
 * File := cx_cxbe_dump.cpp
 * Desc := Xbox Executable class
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice, 
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Aaron "Caustik" Robinson nor the names of its 
 *   contributors may be used to endorse or promote products derived from this 
 *   software without specific prior written permission.
 * 
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 *   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 *   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 *   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
 * 
 *****************************************************************************/

#include "cxbe.h"

bool cx_cxbe::dump_info(FILE *p_file)
{
    /*! sanity check */
    if(p_file == 0) { return false; }

    fprintf(p_file, "  __  __  __                  __           \n");
    fprintf(p_file, " |  ||__||  |--..----..--.--.|  |--..-----.\n");
    fprintf(p_file, " |  ||  ||  _  ||  __||_   _||  _  ||  -__|\n");
    fprintf(p_file, " |__||__||_____||____||__.__||_____||_____|\n");
    fprintf(p_file, "\n");
    fprintf(p_file, "Xbe File information generated by libcxbe (Version " CX_CXBE_VERSION ")\n");
    fprintf(p_file, "\n");
    fprintf(p_file, "Project : http://www.caustik.com/cxbx/\n");
    fprintf(p_file, "Source  : http://sourceforge.net/projects/cxbx/\n");
    fprintf(p_file, "\n");
    fprintf(p_file, "Title Name : \"%s\"\n", ascii_title);
    fprintf(p_file, "\n");
    fprintf(p_file, "Dumping Xbe Image Header...\n");
    fprintf(p_file, "\n");   
    fprintf(p_file, "Magic Number                     : XBEH\n");

    // print digital signature
    {
        int x, y;

        fprintf(p_file, "Digitial Signature               : <Hex Dump>");

        for(y=0;y<16;y++)
        {
            fprintf(p_file, "\n                                   ");

            for(x=0;x<16;x++)
            {
                fprintf(p_file, "%.02X", image_header.pbDigitalSignature[y*16+x]);
            }
        }

        fprintf(p_file, "\n                                   </Hex Dump>\n");
    }

    fprintf(p_file, "Base Address                     : 0x%.08X\n", image_header.dwBaseAddr);
    fprintf(p_file, "Size of Headers                  : 0x%.08X\n", image_header.dwSizeofHeaders);
    fprintf(p_file, "Size of Image                    : 0x%.08X\n", image_header.dwSizeofImage);
    fprintf(p_file, "Size of Image Header             : 0x%.08X\n", image_header.dwSizeofImageHeader);
    fprintf(p_file, "TimeDate Stamp                   : 0x%.08X (%s)\n", image_header.dwTimeDate, get_time_string(image_header.dwTimeDate).c_str());
    fprintf(p_file, "Certificate Address              : 0x%.08X\n", image_header.dwCertificateAddr);
    fprintf(p_file, "Number of Sections               : 0x%.08X\n", image_header.dwSections);
    fprintf(p_file, "Section Headers Address          : 0x%.08X\n", image_header.dwSectionHeadersAddr);

    /*! display init flags */
    {
        fprintf(p_file, "Init Flags                       : 0x%.08X ", image_header.u_init_flags.dwInitFlags);

        if(image_header.u_init_flags.init_flags.bMountUtilityDrive)
        {
            fprintf(p_file, "[Mount Utility Drive] ");
        }

        if(image_header.u_init_flags.init_flags.bFormatUtilityDrive)
        {
            fprintf(p_file, "[Format Utility Drive] ");
        }

        if(image_header.u_init_flags.init_flags.bLimit64MB)
        {
            fprintf(p_file, "[Limit Devkit Run Time Memory to 64MB] ");
        }

        if(!image_header.u_init_flags.init_flags.bDontSetupHarddisk)
        {
            fprintf(p_file, "[Setup Harddisk] ");
        }

        fprintf(p_file, "\n");
    }

    fprintf(p_file, "Entry Point                      : 0x%.08X (Retail: 0x%.08X, Debug: 0x%.08X)\n", image_header.dwEntryAddr, image_header.dwEntryAddr ^ CX_CXBE_XOR_KEY_EP_RETAIL, image_header.dwEntryAddr ^ CX_CXBE_XOR_KEY_EP_DEBUG);
    fprintf(p_file, "TLS Address                      : 0x%.08X\n", image_header.dwTLSAddr);
    fprintf(p_file, "(PE) Stack Commit                : 0x%.08X\n", image_header.dwPeStackCommit);
    fprintf(p_file, "(PE) Heap Reserve                : 0x%.08X\n", image_header.dwPeHeapReserve);
    fprintf(p_file, "(PE) Heap Commit                 : 0x%.08X\n", image_header.dwPeHeapCommit);
    fprintf(p_file, "(PE) Base Address                : 0x%.08X\n", image_header.dwPeBaseAddr);
    fprintf(p_file, "(PE) Size of Image               : 0x%.08X\n", image_header.dwPeSizeofImage);
    fprintf(p_file, "(PE) Checksum                    : 0x%.08X\n", image_header.dwPeChecksum);
    fprintf(p_file, "(PE) TimeDate Stamp              : 0x%.08X (%s)\n", image_header.dwPeTimeDate, get_time_string(image_header.dwPeTimeDate).c_str());
    fprintf(p_file, "Debug Pathname Address           : 0x%.08X (\"%s\")\n", image_header.dwDebugPathnameAddr, parse_ascii(image_header.dwDebugPathnameAddr).c_str());
    fprintf(p_file, "Debug Filename Address           : 0x%.08X (\"%s\")\n", image_header.dwDebugFilenameAddr, parse_ascii(image_header.dwDebugFilenameAddr).c_str());
    fprintf(p_file, "Debug Unicode filename Address   : 0x%.08X (\"%s\")\n", image_header.dwDebugUnicodeFilenameAddr, parse_utf16(image_header.dwDebugUnicodeFilenameAddr).c_str());
    fprintf(p_file, "Kernel Image Thunk Address       : 0x%.08X (Retail: 0x%.08X, Debug: 0x%.08X)\n", image_header.dwKernelImageThunkAddr, image_header.dwKernelImageThunkAddr ^ CX_CXBE_XOR_KEY_KT_RETAIL, image_header.dwKernelImageThunkAddr ^ CX_CXBE_XOR_KEY_KT_DEBUG);
    fprintf(p_file, "NonKernel Import Dir Address     : 0x%.08X\n", image_header.dwNonKernelImportDirAddr);
    fprintf(p_file, "Library Versions                 : 0x%.08X\n", image_header.dwLibraryVersions);
    fprintf(p_file, "Library Versions Address         : 0x%.08X\n", image_header.dwLibraryVersionsAddr);
    fprintf(p_file, "Kernel Library Version Address   : 0x%.08X\n", image_header.dwKernelLibraryVersionAddr);
    fprintf(p_file, "XAPI Library Version Address     : 0x%.08X\n", image_header.dwXAPILibraryVersionAddr);
    fprintf(p_file, "Logo Bitmap Address              : 0x%.08X\n", image_header.dwLogoBitmapAddr);
    fprintf(p_file, "Logo Bitmap Size                 : 0x%.08X\n", image_header.dwSizeofLogoBitmap);
    fprintf(p_file, "\n");
    fprintf(p_file, "Dumping Xbe Certificate...\n");
    fprintf(p_file, "\n");
    fprintf(p_file, "Size of Certificate              : 0x%.08X\n", certificate.dwSize);
    fprintf(p_file, "TimeDate Stamp                   : 0x%.08X (%s)\n", certificate.dwTimeDate, get_time_string(certificate.dwTimeDate).c_str());
    fprintf(p_file, "Title ID                         : 0x%.08X\n", certificate.dwTitleId);
    fprintf(p_file, "Title Name                       : \"%s\"\n", ascii_title);

    // print alternate title IDs
    {
        fprintf(p_file, "Alternate Titles IDs             : ");

        uint32 v;

        for(v=0;v<0x10;v++)
        {
            if(v != 0)
            {
                fprintf(p_file, "                                   ");
            }

            fprintf(p_file, "0x%.08X", certificate.dwAlternateTitleId[v]);

            if(v != 0x0F)
            {
                fprintf(p_file, "\n");
            }
        }

        fprintf(p_file, "\n");
    }

    fprintf(p_file, "Allowed Media                    : 0x%.08X\n", certificate.dwAllowedMedia);
    fprintf(p_file, "Game Region                      : 0x%.08X\n", certificate.dwGameRegion);
    fprintf(p_file, "Game Ratings                     : 0x%.08X\n", certificate.dwGameRatings);
    fprintf(p_file, "Disk Number                      : 0x%.08X\n", certificate.dwDiskNumber);
    fprintf(p_file, "Version                          : 0x%.08X\n", certificate.dwVersion);

    /*! print LAN key */
    {
        fprintf(p_file, "LAN Key                          : ");

        uint32 v;

        for(v=0;v<16;v++)
        {
            fprintf(p_file, "%.02X", certificate.bzLanKey[v]);
        }

        fprintf(p_file, "\n");
    }

    /*! print signature key */
    {
        fprintf(p_file, "Signature Key                    : ");

        uint32 v;        

        for(v=0;v<16;v++)
        {
            fprintf(p_file, "%.02X", certificate.bzSignatureKey[v]);
        }

        fprintf(p_file, "\n");
    }

    /*! print alternate signature keys */
    {
        fprintf(p_file, "Title Alternate Signature Keys   : <Hex Dump>");

        uint32 y, x;

        for(y=0;y<16;y++)
        {
            fprintf(p_file, "\n                                   ");

            for(x=0;x<16;x++)
            {
                fprintf(p_file, "%.02X", certificate.bzTitleAlternateSignatureKey[y][x]);
            }
        }

        fprintf(p_file, "\n                                   </Hex Dump>\n");
    }

    fprintf(p_file, "\n");   
    fprintf(p_file, "Dumping Xbe Section Headers...\n");
    fprintf(p_file, "\n");   

    /*! print section headers */
    {
        uint32 v;

        for(v=0;v<image_header.dwSections;v++)
        {
            fprintf(p_file, "Section Name                     : 0x%.08X (\"%s\")\n", p_section_header[v].dwSectionNameAddr, section_name[v]);

            /*! print section flags */
            {
                fprintf(p_file, "Flags                            : 0x%.08X ", p_section_header[v].u_flags.dwFlags);

                if(p_section_header[v].u_flags.flags.bWritable)
                {
                    fprintf(p_file, "(Writable) ");
                }

                if(p_section_header[v].u_flags.flags.bPreload)
                {
                    fprintf(p_file, "(Preload) ");
                }

                if(p_section_header[v].u_flags.flags.bExecutable)
                {
                    fprintf(p_file, "(Executable) ");
                }

                if(p_section_header[v].u_flags.flags.bInsertedFile)
                {
                    fprintf(p_file, "(Inserted File) ");
                }

                if(p_section_header[v].u_flags.flags.bHeadPageRO)
                {
                    fprintf(p_file, "(Head Page RO) ");
                }

                if(p_section_header[v].u_flags.flags.bTailPageRO)
                {
                    fprintf(p_file, "(Tail Page RO) ");
                }

                fprintf(p_file, "\n");
            }

            fprintf(p_file, "Virtual Address                  : 0x%.08X\n", p_section_header[v].dwVirtualAddr);
            fprintf(p_file, "Virtual Size                     : 0x%.08X\n", p_section_header[v].dwVirtualSize);
            fprintf(p_file, "Raw Address                      : 0x%.08X\n", p_section_header[v].dwRawAddr);
            fprintf(p_file, "Size of Raw                      : 0x%.08X\n", p_section_header[v].dwSizeofRaw);
            fprintf(p_file, "Section Name Address             : 0x%.08X\n", p_section_header[v].dwSectionNameAddr);
            fprintf(p_file, "Section Reference Count          : 0x%.08X\n", p_section_header[v].dwSectionRefCount);
            fprintf(p_file, "Head Shared Reference Count Addr : 0x%.08X\n", p_section_header[v].dwHeadSharedRefCountAddr);
            fprintf(p_file, "Tail Shared Reference Count Addr : 0x%.08X\n", p_section_header[v].dwTailSharedRefCountAddr);

            /*! print section digest */
            {
                fprintf(p_file, "Section Digest                   : ");

                uint32 s;

                for(s=0;s<20;s++)
                {
                    fprintf(p_file, "%.02X", p_section_header[v].bzSectionDigest[s]);
                }

                fprintf(p_file, "\n");
            }

            fprintf(p_file, "\n");
        }
    }

    fprintf(p_file, "Dumping Xbe Library Versions...\n");
    fprintf(p_file, "\n");   

    /*! print xbe library versions */
    {
        if( (p_library_version == 0) || (image_header.dwLibraryVersions == 0) )
        {
            fprintf(p_file, "(This Xbe contains no Library Versions)\n");
            fprintf(p_file, "\n");
        }
        else
        {
            uint32 v;

            for(v=0;v<image_header.dwLibraryVersions;v++)
            {
                char library_name[9] = { 0 };

                strncpy(library_name, p_library_version[v].szName, 8);

                fprintf(p_file, "Library Name                     : %s\n", library_name);
                fprintf(p_file, "Version                          : %d.%d.%d\n", p_library_version[v].wMajorVersion, p_library_version[v].wMinorVersion, p_library_version[v].wBuildVersion);
 
                /*! print xbe library version flags */
                {
                    fprintf(p_file, "Flags                            : ");

                    fprintf(p_file, "QFEVersion : 0x%.04X, ", p_library_version[v].u_flags.flags.QFEVersion);

                    if(p_library_version[v].u_flags.flags.bDebugBuild)
                    {
                        fprintf(p_file, "Debug, ");
                    }
                    else
                    {
                        fprintf(p_file, "Retail, ");
                    }

                    switch(p_library_version[v].u_flags.flags.Approved)
                    {
                        case 0:
                            fprintf(p_file, "Unapproved");
                            break;
                        case 1:
                            fprintf(p_file, "Possibly Approved");
                            break;
                        case 2:
                            fprintf(p_file, "Approved");
                            break;
                    }

                    fprintf(p_file, "\n");
                }

                fprintf(p_file, "\n");
            }
        }
    }

    fprintf(p_file, "Dumping Thread Local Storage information...\n");
    fprintf(p_file, "\n");   

    /*! print thread local storage information */
    if(p_tls != 0)
    {
        fprintf(p_file, "Data Start Address               : 0x%.08X\n", p_tls->dwDataStartAddr);
        fprintf(p_file, "Data End Address                 : 0x%.08X\n", p_tls->dwDataEndAddr);
        fprintf(p_file, "TLS Index Address                : 0x%.08X\n", p_tls->dwTLSIndexAddr);
        fprintf(p_file, "TLS Callback Address             : 0x%.08X\n", p_tls->dwTLSCallbackAddr);
        fprintf(p_file, "Size of Zero Fill                : 0x%.08X\n", p_tls->dwSizeofZeroFill);
        fprintf(p_file, "Characteristics                  : 0x%.08X\n", p_tls->dwCharacteristics);
    }
    else
    {
        fprintf(p_file, "(This Xbe contains no Thread Local Storage information)\n");
    }

    return true;
}

